# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lynix < Formula
  desc "TUI-first CLI tool for API testing and functional validation"
  homepage "https://github.com/aalvaropc/lynix"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aalvaropc/lynix/releases/download/v0.1.0/lynix_0.1.0_darwin_amd64.tar.gz"
      sha256 "54a71970d568a746045a54ac2a48a95b20f830d45c06ad366946cd50aa5643e9"

      define_method(:install) do
        bin.install "lynix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aalvaropc/lynix/releases/download/v0.1.0/lynix_0.1.0_darwin_arm64.tar.gz"
      sha256 "fdd8c6df0913cd51d332aa2373f9f540a0b25f872aa7f38dc74148832a93daa2"

      define_method(:install) do
        bin.install "lynix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aalvaropc/lynix/releases/download/v0.1.0/lynix_0.1.0_linux_amd64.tar.gz"
      sha256 "15781472e5accece842793474becf9e3e5a8804a0a8741cd82d931f74d743983"
      define_method(:install) do
        bin.install "lynix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aalvaropc/lynix/releases/download/v0.1.0/lynix_0.1.0_linux_arm64.tar.gz"
      sha256 "981462ea853f6004978897cd268fe481d23ac8e97b66b5e06ed2fb72465a4faa"
      define_method(:install) do
        bin.install "lynix"
      end
    end
  end

  test do
    system "#{bin}/lynix", "version"
  end
end
